# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowstateTelemetry < Formula
  desc "Configure AI coding tools to emit telemetry to Flowstate"
  homepage "https://www.flowstate.inc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.0.0/flowstate-telemetry_1.0.0_darwin_amd64.tar.gz"
      sha256 "ebb2fb193eb8ef49ae4ed1a63e7bd0efb6c6e54bdd842194df0f7d9febba1239"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.0.0/flowstate-telemetry_1.0.0_darwin_arm64.tar.gz"
      sha256 "ea168bc553345155e8385670173616b35fec45968b9dbd25cc14b7ea747b8743"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.0.0/flowstate-telemetry_1.0.0_linux_amd64.tar.gz"
      sha256 "6d96264165860dae84d922c0ac5b3789538cd26c2b0bc72fa28c6d949af25e4a"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.0.0/flowstate-telemetry_1.0.0_linux_arm64.tar.gz"
      sha256 "605f5e2d2669f516fcf369fb923cb08e613afe77886d246dc68a4e32048378e5"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  test do
    system "#{bin}/flowstate-telemetry", "status"
  end
end
