# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowstateTelemetry < Formula
  desc "Configure AI coding tools to emit telemetry to Flowstate"
  homepage "https://www.flowstate.inc"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.1.0/flowstate-telemetry_1.1.0_darwin_amd64.tar.gz"
      sha256 "8296d83fda710d3ff491714d4823decbdfa057bd7f8ecb681684a05c7d343a09"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.1.0/flowstate-telemetry_1.1.0_darwin_arm64.tar.gz"
      sha256 "ee371628a0d7b41b81e053f599d6b92ff94db20680fe3e7b962609281f31c9f5"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.1.0/flowstate-telemetry_1.1.0_linux_amd64.tar.gz"
      sha256 "264746d758e6e7fb43e03e4da75cfcd3866a21615db43ddbd6c93e11c85f87a4"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.1.0/flowstate-telemetry_1.1.0_linux_arm64.tar.gz"
      sha256 "a9978d7a566a5e557d06092b57ee3b69bc0502182002026d79a1cba55504cf54"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  test do
    system "#{bin}/flowstate-telemetry", "status"
  end
end
