# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowstateTelemetry < Formula
  desc "Configure AI coding tools to emit telemetry to Flowstate"
  homepage "https://www.flowstate.inc"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.2.0/flowstate-telemetry_1.2.0_darwin_amd64.tar.gz"
      sha256 "d8ea80917f8292618fcf7b116342973e5d487f356448d5a057a2a2fcac33b76c"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.2.0/flowstate-telemetry_1.2.0_darwin_arm64.tar.gz"
      sha256 "c4cdd38873bc2cc73134346e3d0a7059c0a06290b6f948d44fdd230af15b11b3"

      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.2.0/flowstate-telemetry_1.2.0_linux_amd64.tar.gz"
      sha256 "a5ddef746a268b4b11aae390d30a2fabd34c51306a5f47d0febe0184ae79bc1a"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meetflowstate/flowstate-telemetry/releases/download/v1.2.0/flowstate-telemetry_1.2.0_linux_arm64.tar.gz"
      sha256 "eb483b850069dffba37cac45c8b627155cf3404f2c173ac09345c0c0e4aa70a3"
      define_method(:install) do
        bin.install "flowstate-telemetry"
      end
    end
  end

  test do
    system "#{bin}/flowstate-telemetry", "status"
  end
end
